config/routes.rb
Rails.application.routes.draw do
 root 'wrappers#index'
  resources :wrappers
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/wrapper.rb
class Wrapper < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/wrappers_controller.rb
class WrappersController < ApplicationController
  before_action :initialize_client
  

  # GET /wrappers or /wrappers.json
  def index 
    
  begin
    @menu = @client.search_menu_items(params[:item])
    rescue RuntimeError
    @error = true
    @response = response.status
   end
  end

  # GET /wrappers/1 or /wrappers/1.json
  def show
    begin
    @search_by_nutrients = @client.search_by_nutrients(params[:min],params[:max],params[:value1],params[:value2 ])
  rescue RuntimeError
    @error = true
   end
  end

  # GET /wrappers/new
  def new
    @wrapper = Wrapper.new
  end

  # GET /wrappers/1/edit
  def edit
  end

  # POST /wrappers or /wrappers.json
  def create
    @wrapper = Wrapper.new(wrapper_params)

    respond_to do |format|
      if @wrapper.save
        format.html { redirect_to @wrapper, notice: "Wrapper was successfully created." }
        format.json { render :show, status: :created, location: @wrapper }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wrapper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wrappers/1 or /wrappers/1.json
  def update
    respond_to do |format|
      if @wrapper.update(wrapper_params)
        format.html { redirect_to @wrapper, notice: "Wrapper was successfully updated." }
        format.json { render :show, status: :ok, location: @wrapper }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wrapper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wrappers/1 or /wrappers/1.json
  def destroy
    @wrapper.destroy
    respond_to do |format|
      format.html { redirect_to wrappers_url, notice: "Wrapper was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wrapper
      @wrapper = Wrapper.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wrapper_params
      params.fetch(:wrapper, {})
    end

    def initialize_client
      @client = Spoonacular::Client.new

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wrappers_helper.rb
module WrappersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsApiWrapperProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/wrappers/_form.html.erb
<%= form_with(model: wrapper) do |form| %>
  <% if wrapper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wrapper.errors.count, "error") %> prohibited this wrapper from being saved:</h2>

      <ul>
        <% wrapper.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wrappers/edit.html.erb
<h1>Editing Wrapper</h1>

<%= render 'form', wrapper: @wrapper %>

<%= link_to 'Show', @wrapper %> |
<%= link_to 'Back', wrappers_path %>

app/views/wrappers/index.html.erb
 <div id="search-bar">
  <%= form_tag(wrappers_path ,method: :get) do %>
    <%=text_field_tag(:item , params[:item] , :size=>"98%")%>
    <%= submit_tag ("Search") %>
    <%end%>
    </div>

   <div class="link"> <button><%=link_to 'Search by nutrients' , wrapper_path(1) %> </button></div>


<%if @error %>
<div id="blank-search"><h1>Check HTTP code for error </h1></div>
<%else%>
  <% if@menu.present? %>
     
        
                        <% if @menu['menuItems'].present? %>
            <div id= "menu-title-list">
                        <%(0...@menu['menuItems'].length).each do |id| %>
                          <div class = "each-title">
                              <h1> Order id <%= @menu['menuItems'][id]['id']%></h1>
                              <h3> <%= @menu['menuItems'][id]['title']%></h2>
                              <h3> <%= @menu['menuItems'][id]['restaurantChain']%></h3>
                              <div id= "image"><img src = <%=@menu['menuItems'][id]['image'] %> alt="Image Unavailable" </img></div>
                              <h3> <%= @menu['menuItems'][id]['servingSize']%></h3>
                          </div>
                          <%end%>
                          <%else%>
                          <div class="error"> <h2>Menu is not available . Try other menu :)</h2></div>
                          <%end%>
                
                 
          </div>
  <%else%>
  <div class ="error"><h2> Please enter any valid food in search bar </h2></div>
  <%end%>
<%end%>






   

app/views/wrappers/new.html.erb
<h1>New Wrapper</h1>

<%= render 'form', wrapper: @wrapper %>

<%= link_to 'Back', wrappers_path %>

app/views/wrappers/show.html.erb
<div id="nutrient-show">
  <%= form_tag(wrapper_path ,method: :get) do %>

   <div class="nutrient-form">
   <%= label_tag(:min, "Nutrient") %>
   <br>
   <%=text_field_tag(:min,params[:min],placeholder:"parameters" )%>
   </div>
<br>
   <div class="nutrient-form">
   <%= label_tag(:value1, "Amount") %>
   <br>
   <%=text_field_tag(:value1,params[:value1], placeholder: "value")%>
   </div>
    <br>
   <div><%= submit_tag ("Search") %></div>
   <br>
   <div class="link"><button><%= link_to 'Search by menu items' , wrappers_path %></button></div>
    
    <%end%>
    </div>

    
    <div id= "show-result">
    <% if @error %>
    <div class="error"><h3> Parameter entered is invalid and check if quota already exceed .
    You can go to this link to view the available parameters for data <a href="https://spoonacular.com/food-api/docs#Search-Recipes-by-Nutrients"> Click here .</a> 
    </h3></div>
    <%else%>
    <%(0...@search_by_nutrients.length).each do |id| %>
        <div class = "each-title">
        
          <h3><%= @search_by_nutrients[id]['title']%></h3>
          <img src = <%= @search_by_nutrients[id]['image'] %> alt="Image is not available :("</img>
          <p> Calories : <%=@search_by_nutrients[id]['calories'] %>
          <p> Fat :<%=@search_by_nutrients[id]['fat'] %>
          <p> Protein :<%=@search_by_nutrients[id]['protein'] %>
          <p> Carbs :<%=@search_by_nutrients[id]['carbs'] %>

        
          </div>
          <%end%>
          <%end%>
          </div>
  


  
  
  